repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      args: [--line-length=79]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.3
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings~=1.6.0
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort